labora.api.url=${LABORA_API_URL:http://localhost:3001}


# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:labify.contato@gmail.com}
spring.mail.password=${MAIL_PASSWORD:luuw wwbj ikah vgau}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET:8625878b114a19868dc5bb6a8b6f5f5f72f4ecbb2c3b42dd6dbec6b787d0a244}

spring.jackson.deserialization.accept-single-value-as-array=true

# Google SSO
labify.sso.google.client.id=${LABIFY_SSO_GOOGLE_CLIENT_ID:}
labify.sso.google.client.secret=${LABIFY_SSO_GOOGLE_CLIENT_SECRET:}
labify.sso.google.redirect.uri=${LABORA_CALLBACK_URL:http://localhost:8080/api/login/google/callback}
labify.sso.google.token.endpoint=https://oauth2.googleapis.com/token
labify.sso.google.scope=openid email profile

app.frontend.url=${APP_FRONTEND_URL:http://localhost:4200}

# Server Config
server.servlet.context-path=/api